name: Deployment

on: [push]

jobs:
  buildJava8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: build string
      run: |
        cd ../
        git config --global user.email "cli@github.com"
        git config --global user.name "Github Actions"
        git clone --depth=1 --branch=master https://github.com/Minxyzgo/KideBuilds ../KideBuilds
        cd ../KideBuilds
        git add .
        git commit -m "Updating to build"
        git push https://Minxyzgo:${{ secrets.API_TOKEN_GITHUB }}@github.com/Minxyzgo/KideBuilds